import { useEffect, useState } from 'react';
import { db } from '../../database/db';
import { createDashboardService, type DashboardMetrics, type DashboardPeriod } from '../../services/dashboardService';
const money=(v:number)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(v)+' FCFA'; const date=(v:string)=>new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
type Preset='today'|'week'|'month'; function periodFor(p:Preset):DashboardPeriod{const now=new Date(),s=new Date(now);if(p==='today')s.setHours(0,0,0,0);if(p==='week'){s.setDate(now.getDate()-6);s.setHours(0,0,0,0)}if(p==='month'){s.setDate(1);s.setHours(0,0,0,0)}return{from:s.toISOString(),to:now.toISOString()}}
const card:React.CSSProperties={border:'1px solid #e5e7eb',borderRadius:14,padding:16,background:'#fff',boxShadow:'0 1px 2px rgba(0,0,0,.04)'};
function TrendChart({metrics}:{metrics:DashboardMetrics}){const points=metrics.trend; if(!points.length)return <p>Aucune donnée de tendance sur la période.</p>; const max=Math.max(...points.map(p=>Math.max(p.revenue,p.grossProfit,Math.max(0,p.netProfit))),1); return <div role="img" aria-label="Évolution quotidienne du chiffre d'affaires et du bénéfice net"><div style={{display:'flex',alignItems:'flex-end',gap:6,height:190,overflowX:'auto',padding:'12px 4px'}}>{points.map(p=>{const revenueH=Math.max(4,p.revenue/max*150),netH=Math.max(2,Math.abs(p.netProfit)/max*150);return <div key={p.date} title={`${p.date} · CA ${money(p.revenue)} · bénéfice net ${money(p.netProfit)}`} style={{minWidth:28,height:170,display:'flex',alignItems:'flex-end',gap:3}}><div style={{width:11,height:revenueH,borderRadius:'4px 4px 0 0',background:'#1f2937'}}/><div style={{width:11,height:netH,borderRadius:'4px 4px 0 0',background:p.netProfit>=0?'#16a34a':'#dc2626'}}/></div>})}</div><div style={{display:'flex',gap:14,fontSize:12}}><span>■ CA</span><span>■ Bénéfice net</span></div><div style={{display:'flex',justifyContent:'space-between',fontSize:11,color:'#64748b',marginTop:6}}><span>{points[0].date}</span><span>{points[points.length-1].date}</span></div></div>}
export function DashboardPage(){const[preset,setPreset]=useState<Preset>('month');const[metrics,setMetrics]=useState<DashboardMetrics|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{let active=true;setLoading(true);setError('');createDashboardService(db).getMetrics(periodFor(preset)).then(r=>{if(active)setMetrics(r)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Impossible de charger le Dashboard.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[preset]);if(loading)return <main style={{padding:20}}><h1>Tableau de bord</h1><p aria-live="polite">Chargement...</p></main>;if(error||!metrics)return <main style={{padding:20}}><h1>Tableau de bord</h1><p role="alert">{error||'Aucune donnée disponible.'}</p></main>;const attentionCount=metrics.outOfStockCount+metrics.lowStockCount;return <main style={{maxWidth:1100,margin:'0 auto',padding:'20px 16px 40px',fontFamily:'system-ui',background:'#f8fafc',minHeight:'calc(100vh - 60px)'}}>
<header style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:16,flexWrap:'wrap',marginBottom:20}}><div><p style={{margin:0,fontSize:13}}>ZOYEQUINAPP</p><h1 style={{margin:'4px 0'}}>Tableau de bord</h1><p style={{margin:0}}>La situation de votre boutique en un coup d'œil.</p></div><label style={{display:'flex',flexDirection:'column',gap:5,fontSize:13}}>Période<select value={preset} onChange={e=>setPreset(e.target.value as Preset)} style={{padding:'10px 12px',borderRadius:10,border:'1px solid #cbd5e1',background:'#fff'}}><option value="today">Aujourd'hui</option><option value="week">7 derniers jours</option><option value="month">Ce mois</option></select></label></header>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12}}><article style={card}><p>Chiffre d'affaires</p><h2>{money(metrics.revenue)}</h2><small>{metrics.salesCount} vente(s)</small></article><article style={card}><p>Bénéfice brut</p><h2>{money(metrics.grossProfit)}</h2><small>Après coût des marchandises</small></article><article style={card}><p>Bénéfice net</p><h2>{money(metrics.netProfit)}</h2><small>Dépenses : {money(metrics.expenses)}</small></article><article style={card}><p>Créances clients</p><h2>{money(metrics.customerReceivables)}</h2><small>À recouvrer</small></article></section>
<section style={{...card,marginTop:12}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><h2 style={{margin:'0 0 4px'}}>Évolution</h2><small>Chiffre d'affaires et bénéfice net par jour</small></div></div><TrendChart metrics={metrics}/></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:12,marginTop:12}}><article style={card}><p>Valeur du stock</p><h2>{money(metrics.stockValue)}</h2><small>Au prix d'achat</small></article><article style={{...card,borderColor:attentionCount?'#f59e0b':'#e5e7eb'}}><p>À surveiller</p><h2>{attentionCount}</h2><small>{metrics.lowStockCount} faible(s), {metrics.outOfStockCount} rupture(s)</small></article></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12,marginTop:12}}><article style={card}><h2>Top produits</h2>{metrics.topProducts.length?<ol>{metrics.topProducts.map(p=><li key={p.productId} style={{marginBottom:10}}><strong>{p.productName}</strong><br/><small>{p.quantity} vendu(s) · {money(p.revenue)} · marge {money(p.grossProfit)}</small></li>)}</ol>:<p>Aucune vente sur la période.</p>}</article><article style={card}><h2>Créances à surveiller</h2>{metrics.receivables.length?<ul>{metrics.receivables.map(r=><li key={r.customerId} style={{marginBottom:10}}><strong>{r.customerName}</strong>{r.customerPhone?` · ${r.customerPhone}`:''}<br/><small>{money(r.balance)} restant sur {money(r.originalAmount)}</small></li>)}</ul>:<p>Aucune créance active.</p>}</article></section>
<section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12,marginTop:12}}><article style={card}><h2>Dernières ventes</h2>{metrics.recentSales.length?<ul>{metrics.recentSales.map(s=><li key={s.id} style={{marginBottom:10}}><strong>{s.receiptNumber}</strong> · {money(s.total)}<br/><small>{s.paymentMethod} · {date(s.createdAt)}</small></li>)}</ul>:<p>Aucune vente sur la période.</p>}</article><article style={card}><h2>Dernières dépenses</h2>{metrics.recentExpenses.length?<ul>{metrics.recentExpenses.map(e=><li key={e.id} style={{marginBottom:10}}><strong>{e.label}</strong> · {money(e.amount)}<br/><small>{e.category} · {date(e.expenseDate)}</small></li>)}</ul>:<p>Aucune dépense sur la période.</p>}</article></section>
<section style={{...card,marginTop:12}}><h2>À retenir</h2><ul><li>{metrics.netProfit>=0?`La période est bénéficiaire de ${money(metrics.netProfit)}.`:`La période est déficitaire de ${money(Math.abs(metrics.netProfit))}.`}</li><li>{metrics.customerReceivables>0?`${money(metrics.customerReceivables)} restent à recouvrer auprès des clients.`:'Aucune créance client en cours.'}</li><li>{metrics.outOfStockCount>0?`${metrics.outOfStockCount} produit(s) sont en rupture et nécessitent une action.`:'Aucune rupture de stock détectée.'}</li></ul></section></main>}
